server:
  port: 8761
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
# sample for multiple eureka's servers
#  instance:
#    hostname: peer1
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://peer1:8090/eureka/,http://peer2:8091/eureka/
