server:
  port: 8084
logging:
  level:
    root: INFO
spring:
  application:
    name: OrdersService
  data:
    mongodb:
      host: ${PRODUCT-DB-HOST:127.0.0.1}
      port: ${PRODUCT-DB-PORT:27017}
      database: ${PRODUCT-DB-NAME:orders}
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: ${eureka_url:http://localhost:8761/eureka/}
orders:
  merchantAccount: ${MERCHANT_ACCOUNT:"5555-0710"}

---

spring:
  profiles: test
  data:
    mongodb:
      host: "localhost"
      port: 0
      database: "orders"
