spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  datasource:
    platform: mysql
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: "sa"
    password: "sa"
    driverClassName: org.h2.Driver