version: "2.1"
services:
  mongodb:
    image: mongo:3.2
    ports:
      - 27017:27017
    healthcheck:
      test: echo 'db.stats().ok'
      interval: 5s
      timeout: 5s
  productcatalog:
      build: .
      depends_on:
        mongodb:
          condition: service_healthy
      links:
        - mongodb
      environment:
        PRODUCTS_DB_URI: mongodb://mongodb:27017/products 
      ports:
        - 8082:8082
