apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  labels:
    app: api-gateway
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8087
  selector:
    app: api-gateway
    tier: backend
  type: NodePort
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: api-gateway
spec:
  selector:
    matchLabels:
      app: api-gateway
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: api-gateway
        tier: backend
    spec:
      containers:
        - image: microservices-shop-sample/api-gateway
          imagePullPolicy: Never
          name: api-gateway
          env:
            - name: USERS_SERVICE
              value: http://userapp/api/users
            - name: ORDERS_SERVICE
              value: http://orders/api/orders
            - name: PRODUCT_CATALOG_SERVICE
              value: http://products-catalog/api/products
          ports:
            - containerPort: 8087
              name: api-gateway
