apiVersion: v1
kind: Service
metadata:
  name: orders
  labels:
    app: orders
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8084
  selector:
    app: orders
    tier: backend
  type: ClusterIP
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: orders
  labels:
    app: orders
spec:
  selector:
    matchLabels:
      app: orders
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: orders
        tier: backend
    spec:
      containers:
        - image: microservices-shop-sample/orders
          imagePullPolicy: Never
          name: orders
          env:
            - name: ORDERS_DB_URI
              value: mongodb://mongo-0.mongo:27017/orders
            - name: PAYMENTS_SERVICE_URI
              value: http://payments
            - name: STOCK_SERVICE_URI
              value: http://stock
          ports:
            - containerPort: 8084
              name: orders