apiVersion: v1
kind: Service
metadata:
  name: payments
  labels:
    app: payments
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8083
  selector:
    app: payments
    tier: backend
  type: ClusterIP
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: payments
  labels:
    app: payments
spec:
  selector:
    matchLabels:
      app: payments
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: payments
        tier: backend
    spec:
      containers:
        - image: microservices-shop-sample/payments
          imagePullPolicy: Never
          name: payments
          env:
            - name: PAYMENTS_DB_URI
              value: mongodb://mongo-0.mongo:27017/payments
          ports:
            - containerPort: 8083
              name: payments
