apiVersion: v1
kind: Service
metadata:
  name: stock
  labels:
    app: stock
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8085
  selector:
    app: stock
    tier: backend
  type: ClusterIP
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: stock
  labels:
    app: stock
spec:
  selector:
    matchLabels:
      app: stock
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: stock
        tier: backend
    spec:
      containers:
        - image: microservices-shop-sample/stock
          imagePullPolicy: Never
          name: stock
          env:
            - name: PAYMENTS_DB_URI
              value: mongodb://mongo-0.mongo:27017/payments
          ports:
            - containerPort: 8085
              name: stock
