server:
  port: 8082
logging:
  level:
    root: INFO
spring:
  application:
    name: ProductCatalog
  data:
    mongodb:
      host: ${PRODUCT-DB-HOST:localhost}
      port: ${PRODUCT-DB-PORT:27017}
      database: ${PRODUCT-DB-NAME:products}
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: ${eureka_url:http://localhost:8761/eureka/}

---

spring:
  profiles: test
  data:
    mongodb:
      host: "localhost"
      port: 0
      database: "products-catalog"

