server:
  port: 8082
logging:
  level:
    root: INFO
spring:
  application:
    name: ProductCatalog
  data:
    mongodb:
      host: ${PRODUCT-DB-HOST:localhost}
      port: ${PRODUCT-DB-PORT:27017}
      database: ${PRODUCT-DB-NAME:products}
---

spring:
  profiles: test
  data:
    mongodb:
      host: "localhost"
      port: 0
      database: "products-catalog"

