version: "2.1"
services:
  userappdb:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${USER_APP_DB_PWD}
      MYSQL_DATABASE: "userapp"
    ports:
      - 3306:3306
    healthcheck:
      test: "/etc/init.d/mysql status"
      interval: 1s
      retries: 120 
#  userapp:
#    build: .
#    depends_on:
#      userappdb:
#        condition: service_healthy
#    links:
#      - userappdb
#    ports:
#      - 8081:8080
#    environment:
#      DB_PASSWORD: ${USER_APP_DB_PWD}
#      DB_USERNAME: "root"
#      DB_HOST: userappdb
#      DB_PORT: 3306

